Add Rancher stack and service to structured data
uphold-forks/logspout pull request #1
Opened 2017-02-22 23:38 UTC by mccricardo

Implements [Add stack and service to logspout](https://jira.uphold.com/browse/INFRA-1167).

Also includes change that does not pump full log on a restart.

2017-02-22 23:39 UTC, ruimarinho commented on router/pump.go
> +		if stackService, ok := container.Config.Labels ["io.rancher.stack_service.name"]; ok {
Extra space after Labels.

2017-02-22 23:42 UTC, mccricardo commented on router/pump.go
> +		if stackService, ok := container.Config.Labels ["io.rancher.stack_service.name"]; ok {
Removed.

2017-03-10 15:27 UTC, alfredopalhares requested changes

2017-03-10 15:27 UTC, masterkorp commented on router/pump.go
> +		case "restart":
Since #2 was merged, these changes can be reverted, right?

2017-03-10 16:04 UTC, alfredopalhares approved these changes
LGTM

2017-03-10 16:04 UTC, merged